/*
 * 
 * [
   {
    "id" : 811820,
    "created_at" : "2011/05/24 22:17:29 +0000",
    "user_id" : 4892289,
    "duration" : 856695,
    "sharing" : "public",
    "tag_list" : "",
    "permalink" : "looking-to-sign-similar-1",
    "description" : "",
    "streamable" : true,
    "downloadable" : false,
    "genre" : "",
    "release" : "",
    "purchase_url" : null,
    "label_id" : null,
    "label_name" : "",
    "type" : "",
    "playlist_type" : "",
    "ean" : "",
    "title" : "Looking to sign similar sounding artists...",
    "release_year" : null,
    "release_month" : null,
    "release_day" : null,
    "license" : "all-rights-reserved",
    "uri" : "https://api.soundcloud.com/playlists/811820",
    "permalink_url" : "http://soundcloud.com/soulive/sets/looking-to-sign-similar-1",
    "artwork_url" : null,
    "user": {
     "id" : 4892289,
     "permalink" : "soulive",
     "username" : "soulive",
     "uri" : "https://api.soundcloud.com/users/4892289",
     "permalink_url" : "http://soundcloud.com/soulive",
     "avatar_url" : "http://i1.sndcdn.com/avatars-000003847912-59qwth-large.jpg?b17c165"
     },
    "tracks": [
     {
      "id" : 15872619,
      "created_at" : "2011/05/24 21:59:37 +0000",
      "user_id" : 4892289,
      "duration" : 259650,
      "commentable" : true,
      "state" : "finished",
      "sharing" : "public",
      "tag_list" : "",
      "permalink" : "joonie-sunshine",
      "description" : "",
      "streamable" : false,
      "downloadable" : false,
      "genre" : "",
      "release" : "",
      "purchase_url" : null,
      "label_id" : null,
      "label_name" : "",
      "isrc" : "",
      "video_url" : null,
      "track_type" : "",
      "key_signature" : "",
      "bpm" : null,
      "title" : "JOONIE - SunShine",
      "release_year" : null,
      "release_month" : null,
      "release_day" : null,
      "original_format" : "mp3",
      "license" : "all-rights-reserved",
      "uri" : "https://api.soundcloud.com/tracks/15872619",
      "permalink_url" : "http://soundcloud.com/soulive/joonie-sunshine",
      "artwork_url" : null,
      "waveform_url" : "http://w1.sndcdn.com/0CiaUHEAZLKu_m.png",
      "user": {
       "id" : 4892289,
       "permalink" : "soulive",
       "username" : "soulive",
       "uri" : "https://api.soundcloud.com/users/4892289",
       "permalink_url" : "http://soundcloud.com/soulive",
       "avatar_url" : "http://i1.sndcdn.com/avatars-000003847912-59qwth-large.jpg?b17c165"
       },
      "playback_count" : 2,
      "download_count" : 0,
      "favoritings_count" : 0,
      "comment_count" : 0,
      "attachments_uri" : "https://api.soundcloud.com/tracks/15872619/attachments"
      },
      {
      "id" : 15872866,
      "created_at" : "2011/05/24 22:03:15 +0000",
      "user_id" : 4892289,
      "duration" : 219538,
      "commentable" : true,
      "state" : "finished",
      "sharing" : "public",
      "tag_list" : "",
      "permalink" : "little-brother-shake-it",
      "description" : "",
      "streamable" : false,
      "downloadable" : false,
      "genre" : "",
      "release" : "",
      "purchase_url" : null,
      "label_id" : null,
      "label_name" : "",
      "isrc" : "",
      "video_url" : null,
      "track_type" : "",
      "key_signature" : "",
      "bpm" : null,
      "title" : "Little Brother - Shake It",
      "release_year" : null,
      "release_month" : null,
      "release_day" : null,
      "original_format" : "mp3",
      "license" : "all-rights-reserved",
      "uri" : "https://api.soundcloud.com/tracks/15872866",
      "permalink_url" : "http://soundcloud.com/soulive/little-brother-shake-it",
      "artwork_url" : null,
      "waveform_url" : "http://w1.sndcdn.com/udqT0CHwpU0K_m.png",
      "user": {
       "id" : 4892289,
       "permalink" : "soulive",
       "username" : "soulive",
       "uri" : "https://api.soundcloud.com/users/4892289",
       "permalink_url" : "http://soundcloud.com/soulive",
       "avatar_url" : "http://i1.sndcdn.com/avatars-000003847912-59qwth-large.jpg?b17c165"
       },
      "playback_count" : 1,
      "download_count" : 0,
      "favoritings_count" : 0,
      "comment_count" : 0,
      "attachments_uri" : "https://api.soundcloud.com/tracks/15872866/attachments"
      },
      {
      "id" : 15873040,
      "created_at" : "2011/05/24 22:05:53 +0000",
      "user_id" : 4892289,
      "duration" : 213005,
      "commentable" : true,
      "state" : "finished",
      "sharing" : "public",
      "tag_list" : "",
      "permalink" : "donnellshawn-midnight-eyes",
      "description" : "",
      "streamable" : false,
      "downloadable" : false,
      "genre" : "",
      "release" : "",
      "purchase_url" : null,
      "label_id" : null,
      "label_name" : "",
      "isrc" : "",
      "video_url" : null,
      "track_type" : "",
      "key_signature" : "",
      "bpm" : null,
      "title" : "DonnellShawn - Midnight Eyes",
      "release_year" : null,
      "release_month" : null,
      "release_day" : null,
      "original_format" : "mp3",
      "license" : "all-rights-reserved",
      "uri" : "https://api.soundcloud.com/tracks/15873040",
      "permalink_url" : "http://soundcloud.com/soulive/donnellshawn-midnight-eyes",
      "artwork_url" : null,
      "waveform_url" : "http://w1.sndcdn.com/1Jl0rzMdsI2J_m.png",
      "user": {
       "id" : 4892289,
       "permalink" : "soulive",
       "username" : "soulive",
       "uri" : "https://api.soundcloud.com/users/4892289",
       "permalink_url" : "http://soundcloud.com/soulive",
       "avatar_url" : "http://i1.sndcdn.com/avatars-000003847912-59qwth-large.jpg?b17c165"
       },
      "playback_count" : 1,
      "download_count" : 0,
      "favoritings_count" : 0,
      "comment_count" : 0,
      "attachments_uri" : "https://api.soundcloud.com/tracks/15873040/attachments"
      },
      {
      "id" : 15873131,
      "created_at" : "2011/05/24 22:07:27 +0000",
      "user_id" : 4892289,
      "duration" : 164502,
      "commentable" : true,
      "state" : "finished",
      "sharing" : "public",
      "tag_list" : "",
      "permalink" : "kev-brown-albany",
      "description" : "",
      "streamable" : false,
      "downloadable" : false,
      "genre" : "",
      "release" : "",
      "purchase_url" : null,
      "label_id" : null,
      "label_name" : "",
      "isrc" : "",
      "video_url" : null,
      "track_type" : "",
      "key_signature" : "",
      "bpm" : null,
      "title" : "Kev Brown - Albany",
      "release_year" : null,
      "release_month" : null,
      "release_day" : null,
      "original_format" : "mp3",
      "license" : "all-rights-reserved",
      "uri" : "https://api.soundcloud.com/tracks/15873131",
      "permalink_url" : "http://soundcloud.com/soulive/kev-brown-albany",
      "artwork_url" : null,
      "waveform_url" : "http://w1.sndcdn.com/MPMs9aeWZo7J_m.png",
      "user": {
       "id" : 4892289,
       "permalink" : "soulive",
       "username" : "soulive",
       "uri" : "https://api.soundcloud.com/users/4892289",
       "permalink_url" : "http://soundcloud.com/soulive",
       "avatar_url" : "http://i1.sndcdn.com/avatars-000003847912-59qwth-large.jpg?b17c165"
       },
      "playback_count" : 4,
      "download_count" : 0,
      "favoritings_count" : 0,
      "comment_count" : 0,
      "attachments_uri" : "https://api.soundcloud.com/tracks/15873131/attachments"
      }
    ]
}
  ]*/

using System;
namespace MonoSoundCloud.Entities
{
	public class Playlist: ISoundCloudEntity
	{
		public static string REST_PATH = "/playlists.json";
			
		public string RestPath { get { return REST_PATH; } }
	
		public Playlist ()
		{
		}
	}
}

